package com.routebox.routebox.exception.user

import com.routebox.routebox.exception.CustomExceptionType
import com.routebox.routebox.exception.common.ConflictException

class UserSocialLoginUidDuplicationException : ConflictException(CustomExceptionType.USER_SOCIAL_LOGIN_UID_DUPLICATION)
