name: CI for dev

on:
    pull_request:
        branches: [ "develop" ]

jobs:
    build:
        name: CI
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'adopt'

            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew

            -   name: Copy Secret
                env:
                    CREATE_SECRET: ${{secrets.ENV_DEV}}
                    CREATE_SECRET_DIR: src/main/resources
                    CREATE_SECRET_DIR_FILE_NAME: env.properties
                run: echo $CREATE_SECRET | base64 --decode > $CREATE_SECRET_DIR/$CREATE_SECRET_DIR_FILE_NAME

            -   name: Build with Gradle
                run: ./gradlew build -Dspring.profiles.active=dev

            -   name: Upload Jacoco Report
                if: ${{ !cancelled() }}
                uses: actions/upload-artifact@v3
                with:
                    name: jacoco-report
                    path: build/reports/jacoco/test/html
